### ISSUE TITLE
Refresh to see new questions.

### ISSUE THREAD

**Issue by ejvelasco** [berkmancenter/question_tool#64]
Why do users have to press "Refresh" when a new question is posted? Shouldn't Meteor take care of updating that automatically?

**Comment by mariamrf** [comment]
Because the positioning of questions is affected by factors other than date of posting so if we let Meteor do its thing with an active instance questions keep changing positions (maybe while someone is reading them or keeping track of them) which isn't very user friendly.

Right now all other things that do not affect positioning (replies, number of votes displayed inside the question, etc) are updated the "Meteor way" but other than that users have to click refresh.

**Comment by sbhayana26** [comment]
Do we have any specific idea (with respect to the Question Tool) in mind that needs to be implemented as a part of this year's GSoC program?

**Comment by jsdiaz** [comment]
Unfortunately the QT was not selected to be part of our 2017 GSoC projects. That said, we are thinking of ways to better integrate new user created posts into instances that does not disrupt other user input and viewing. We will be looking to implement these in a future version.
